Added check - abort when no google cloud env is detected

diff --git a/gopath/bin/createserver b/gopath/bin/createserver
--- a/gopath/bin/createserver
+++ b/gopath/bin/createserver
@@ -1,5 +1,11 @@
 #!/bin/bash -e
 # for safety reasons, abort on all errors -> "-e"
+
+if ! [ "CLOUD_SHELL" == "true" ] ; then
+	echo 'ERROR: No Google Cloud Shell environment detected. Aborting.'
+	exit 1
+fi
+
 cd ~ # just to play it safe, we'll chdir to our own homedir
 . ~/.gcs-x2go # now let's source the config file
 
diff --git a/gopath/bin/destroyserver b/gopath/bin/destroyserver
--- a/gopath/bin/destroyserver
+++ b/gopath/bin/destroyserver
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+if ! [ "CLOUD_SHELL" == "true" ] ; then
+	echo 'ERROR: No Google Cloud Shell environment detected. Aborting.'
+	exit 1
+fi
+
 cd ~ # just to play it safe, we'll chdir to our own homedir
 . ~/.gcs-x2go # now let's source the config file
 
diff --git a/gopath/bin/startserver-html5 b/gopath/bin/startserver-html5
--- a/gopath/bin/startserver-html5
+++ b/gopath/bin/startserver-html5
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+if ! [ "CLOUD_SHELL" == "true" ] ; then
+	echo 'ERROR: No Google Cloud Shell environment detected. Aborting.'
+	exit 1
+fi
+
 . ~/gopath/bin/startserver-main # source the main script
 
 #sudo chroot $SERVERNAME service tor stop # make sure tor is stopped in the changeroot
diff --git a/gopath/bin/startserver-reversetunnel b/gopath/bin/startserver-reversetunnel
--- a/gopath/bin/startserver-reversetunnel
+++ b/gopath/bin/startserver-reversetunnel
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+if ! [ "CLOUD_SHELL" == "true" ] ; then
+	echo 'ERROR: No Google Cloud Shell environment detected. Aborting.'
+	exit 1
+fi
+
 . ~/gopath/bin/startserver-main # source the main script
 serve_keyfile
 sudo chroot $SERVERNAME ssh -R2345:127.0.0.1:222 -p $REMOTEPORT -l $REMOTEUSER $REMOTESERVER # start the reverse tunnel
diff --git a/gopath/bin/thawserver b/gopath/bin/thawserver
--- a/gopath/bin/thawserver
+++ b/gopath/bin/thawserver
@@ -1,5 +1,10 @@
 #!/bin/bash -e
 
+if ! [ "CLOUD_SHELL" == "true" ] ; then
+	echo 'ERROR: No Google Cloud Shell environment detected. Aborting.'
+	exit 1
+fi
+
 # Google prefers tmux over screen; it's installed already and cloud shell via
 # Web Browser uses it by default, so make sure we're using it too - this is
 # for connecting directly via "gcloud cloud-shell ssh", which normally doesn't
