added lots of comments

diff --git a/gopath/bin/destroyserver b/gopath/bin/destroyserver
--- a/gopath/bin/destroyserver
+++ b/gopath/bin/destroyserver
@@ -1,24 +1,33 @@
 #!/bin/bash
-cd ~
-. ~/.gcs-x2go
-[ -z "$SERVERNAME" ] && exit 1
-if [ "$SERVER_USE_ROOT" = "true" ] ; then
+cd ~ # just to play it safe, we'll chdir to our own homedir
+. ~/.gcs-x2go # now let's source the config file
+
+[ -z "$SERVERNAME" ] && exit 1 # no server name? That's a hard error, so let's bail out
+
+if [ "$SERVER_USE_ROOT" = "true" ] ; then # prepend / if server changeroot is in root directory
 	export SERVERNAME="/$SERVERNAME"
 fi
+
+# stop services running in the chroot
 sudo chroot $SERVERNAME service tor stop
 sudo chroot $SERVERNAME service ssh stop
-sudo umount $SERVERNAME/dev/pts $SERVERNAME/dev/shm $SERVERNAME/proc $SERVERNAME/sys $SERVERNAME/home
+
+sudo umount $SERVERNAME/dev/pts $SERVERNAME/dev/shm $SERVERNAME/proc $SERVERNAME/sys $SERVERNAME/home # unmount our bindmounts to clean things up
+
+# check if the user home directory is still mounted (our bindmount for persistence)
 while grep -q "$SERVERNAME/home" /etc/mtab ; do
-	while ! sudo umount $SERVERNAME/home ; do
-		sudo lsof | grep "$SERVERNAME/home"
-		sleep 1
+	while ! sudo umount $SERVERNAME/home ; do # keep trying to umount it
+		sudo lsof | grep "$SERVERNAME/home" # list open files in the mount path if umount failed
+		sleep 1 # the user needs a moment to read the error message ...
 	done
 done
+
+# now remove changeroot directory (but nothing on mounted directories underneath it)
 if sudo rm -rf --one-file-system $SERVERNAME ; then
-	echo "All done."
+	echo "All done." # report success
 else
-	while ! sudo umount $SERVERNAME/home ; do
-		sudo lsof | grep "$SERVERNAME/home"
-		sleep 1
+	while ! sudo umount $SERVERNAME/home ; do # same as above, if the umount failed, keep retrying it
+		sudo lsof | grep "$SERVERNAME/home" # and list which files are responsible for the failure
+		sleep 1 # the user needs a moment to read the error message ...
 	done
 fi
